edition = "2021"
newline_style = "Unix"
format_code_in_doc_comments = true
reorder_impl_items = true
comment_width = 80
wrap_comments = true
normalize_comments = true
imports_granularity = "crate"
group_imports = "StdExternalCrate"
